---
- name: set vars
  set_fact:
    docker_image: '{{ role_archisteamfarm_image }}'
    docker_container: '{{ role_archisteamfarm_container }}'
    docker_puid: '{{ role_archisteamfarm_puid }}'
    docker_pgid: '{{ role_archisteamfarm_pgid }}'
    docker_dir_config: '{{ role_archisteamfarm_dir }}/config'
    docker_dir_plugins: '{{ role_archisteamfarm_dir }}/plugins'
    docker_network: '{{ role_archisteamfarm_network }}'

- name: Create config directory
  ansible.builtin.file:
    path: '{{ docker_dir_config }}'
    state: directory
    owner: '{{ docker_puid }}'
    group: '{{ docker_pgid }}'
    mode: 0755

- name: Create plugins directory
  ansible.builtin.file:
    path: '{{ docker_dir_plugins }}'
    state: directory
    owner: '{{ docker_puid }}'
    group: '{{ docker_pgid }}'
    mode: 0755

- name: Ensure image is pulled
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: "{{ docker_container }}"
  register: result

- name: Create network
  community.docker.docker_network:
    name: "{{ docker_network }}"
    driver_options:
          com.docker.network.bridge.name: "br-{{ docker_network }}"

- name: Create archisteamfarm container
  community.docker.docker_container:
    image: '{{ docker_image }}'
    volumes:
     - '{{ docker_dir_config }}:/app/config:Z'
     - '{{ docker_dir_plugins }}:/app/plugins:Z'
    name: "{{ docker_container }}"
    networks:
     - name: "{{ docker_network }}"
    restart_policy: unless-stopped
    state: started
  when:
    pulled.changed
    or
    result.exists == false
